teracy-dev:
  # teracy-dev location specification
  location:
    git: https://github.com/teracyhq/dev.git
    branch: develop
    sync: true

  # teracy-dev-entry auto update
  entry_location:
    git: https://github.com/teracyhq-incubator/teracy-dev-entry-k8s.git
    branch: develop
    sync: true

  extensions:

    # buggy: https://github.com/teracyhq/dev/issues/453
    - _id: "0"
      location: # auto download the extension into the lookup_path
        git: https://github.com/teracyhq-incubator/teracy-dev-core.git
        branch: develop

    - _id: "entry-0"
      path:
        extension: teracy-dev-essential
      location:
        git: https://github.com/teracyhq-incubator/teracy-dev-essential.git
        branch: develop
      require_version: ">= 0.1.0-SNAPSHOT"
      enabled: true

    - _id: "entry-1"
      path:
        extension: teracy-dev-k8s
      location:
        git: https://github.com/teracyhq-incubator/teracy-dev-k8s.git
        branch: develop
        # tag:
        # ref:
      require_version: ">= 0.1.0, < 0.2.0"
      enabled: true
